### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/connector-telephony#106]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [ ] asterisk_click2dial - By @alexis-via - #109 
- [x] base_phone - By @sylvain-garancher - #107 
- [ ] base_phone_popup
- [ ] crm_claim_phone
- [ ] crm_phone - By @alexis-via - #109 
- [ ] event_phone - By @alexis-via - #109 
- [ ] hr_phone - By @alexis-via - #109 
- [ ] hr_recruitment_phone - By @alexis-via - #109 
- [ ] ovh_telephony_connector

**Comment by Garamotte** [comment]
Migration of the base_phone module here : https://github.com/OCA/connector-telephony/pull/107
