### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/connector-telephony#148]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] asterisk_click2dial
- [ ] base_phone
- [ ] base_phone_popup
- [ ] base_sms_client
- [ ] crm_phone
- [ ] event_phone
- [ ] hr_phone - By @fmdl - #153 
- [ ] hr_recruitment_phone
- [ ] ovh_sms_client
- [ ] ovh_telephony_connector

**Comment by develroo** [comment]
Has there been any progress on this milestone? If not what is needed to help things along?

**Comment by pedrobaeza** [comment]
Nothing except what you see that has been reported here. If you want to contribute, you can migrate any of the pending modules or finance a contributor to do it.

**Comment by develroo** [comment]
OK I am struggling a little to find where all the modules are living? I found asterisk_click2dial living here

 https://github.com/xoes-oca/asterisk_click2dial.git 

And managed to convert it to python3 and it installed with no errors. 

But where are all the other modules? base_phone base_phone_popup etc. I don't  see them in your repository. 

Also I am not exactly sure what the stub repo of connector-telephony supposed to do. I don't see any configs in that repo to pull in any modules or anything.

What am I missing? 

Thanks.

**Comment by pedrobaeza** [comment]
No, they are here in this repository, on the previous branch: https://github.com/OCA/connector-telephony/tree/10.0

Use https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0 that is referred also in the beginning of this issue.

**Comment by Garamotte** [comment]
Note that the `base_phone` module could be replaced by the standard [`phone_validation`](https://github.com/odoo/odoo/tree/11.0/addons/phone_validation) module (at least some parts of it, I didn't check the whole module).

**Comment by develroo** [comment]
> Note that the base_phone module could be replaced by the standard phone_validation module (at least some parts of it, I didn't check the whole module).

Why is that so ? I mean I can understand if a module has superseded it but from what I can understand you need both base_phone and base_phone_popup to function correctly. 

I don't think it is solely about phone validation in any case , is it ?

**Comment by aitorbouzas** [comment]
I'm willing to migrate to 11.0 the `asterisk_click2dial`.
How should I work in the `base_phone` module? Should it be refactored because of [`phone_validation`](https://github.com/odoo/odoo/tree/11.0/addons/phone_validation)? Should it be migrate as it is?
@sylvain-garancher  @pedrobaeza

**Comment by pedrobaeza** [comment]
@aitorbouzas I think we should refactor it for using the core new module. Is acceptable for you?

**Comment by aitorbouzas** [comment]
Refactor `base_phone` or `asterisk_click2dial`? Anyway, we'll migrate it later in time since the need of the module was delayed for our customer.

**Comment by pedrobaeza** [comment]
Well, you have to see if `base_phone` is totally replaceable by `phone_validation`, and if so, use the core one in `asterisk_click2dial` instead of `base_phone`, deprecating it.

**Comment by develroo** [comment]
I think so long as the key features are portable then the rest can be worked on later. Key features to me are click to dial and pop up alerts with maybe a link on incoming calls. 

All the things they [show in this other module](https://www.youtube.com/watch?v=0qWV0htQfwQ) (which does not look like it is being maintained) would be nice but not urgent as the basic functionality.

**Comment by pedrobaeza** [comment]
@alexis-via please update what you have migrated here.

**Comment by develroo** [comment]
Hang on , is the effort to port to v12 or v11? Because I had a quick look at v11 but as I have other commitments I could not see an obvious upgrade path without knowing the changes to OCA templates intimately.

I am not expecting to deploy this for at least 6 months but I would like to know if I should be concentrating on learning the changes in v12 rather than v11 ?
