### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/connector-telephony#275]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list
- [x] asterisk_click2dial - By @luisDIXMIT - #319
- [ ] base_phone - By @luisDIXMIT - #318
- [ ] crm_phone - By @TelmoSuarezConinpe - #302
- [x] sms_twilio - By @AlexPForgeFlow - #306

**Comment by intero-chz** [comment]
Is this repo dead? There was no migration issue for version 15. Just asking. If it's dead then why: no contributers anymore or no one using these modules anymore?

**Comment by pedrobaeza** [comment]
No contributors on odd versions. @alexis-via is one of the contributors of even versions.

**Comment by intero-chz** [comment]
Ah okay, thanks for the answer. @pedrobaeza

**Comment by Behrouz-m** [comment]
is there any plan to upgrade modules to odoo 16?

**Comment by legacyplumbing** [comment]
Without an upgrade to odoo 16, myself and many others will be paying for an alternate.
My question here is... What would it cost to complete branch 16.0?
I have no idea as to the amount of work that goes into it... but I am sure there would be others whom would pitch in as well.
We may not be able to cover it all... I would like to keep it open to all (keeping it within OCA)... will be more people testing and improving as far as I am concerned.
Thanks to all contributors for getting things this far.

**Comment by etobella** [comment]
Check on the PRs, some of the modules are already there :smile: 

For example:

https://github.com/OCA/connector-telephony/pull/319
