### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/connector-telephony#66]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [ ] base_phone - https://github.com/OCA/connector-telephony/pull/83
- [ ] crm_phone
- [ ] hr_phone
- [ ] hr_recruitment_phone
- [ ] asterisk_click2dial_crm
- [ ] crm_claim_phone
- [ ] asterisk_click2dial
- [ ] ovh_telephony_connector
- [ ] event_phone
- [ ] base_phone_popup

**Comment by shainalsutaria** [comment]
Thanks for updating this to 9.0

**Comment by jmalinens** [comment]
@pedrobaeza check pull request #67. I have already migrated to Odoo 9 and use it

**Comment by pedrobaeza** [comment]
Hi, @jmalinens, I only created the issue via an automated migration script, but I can't review all the migration PRs. People from this area should do. From a general review perspective, I can say you that you must do one PR per module migrated, not everything in one big PR. Then, put here the links to be taken into account for reviewers.

**Comment by jmalinens** [comment]
Sure. Will do that on spare time

**Comment by cybersthang** [comment]
I can't install with odoo v9, Can you help me ?.
I have copy all source and move to addons but i can't see all module, i can see module base_phone and install it however i can't see config run it.
